---
title: "Data Analysis Replication"
author: "Avery Shepherd"
date: "4/7/2021"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	warning = TRUE,
	message = TRUE,
	comment = "##",
	prompt = FALSE,
	tidy = TRUE,
	tidy.opts = list(blank = FALSE, width.cutoff = 75),
	fig.path = "img/",
	fig.align = "center"
)
```

```{r}
library(tidyverse)
```


## Introduction

[Include a summary of the paper you are reanalyzing data from]

## Visualization of Data
```{r}
mydata <- haven::read_dta("election_panel_2008_2016.dta")
mydata %>% arrange(state) %>% head()
```



```{r}
hist2012 <- mydata %>% filter(year == 2012) %>%
  ggplot(aes(x = pctic_0400, 
             after_stat(density), 
             group = expansion, 
             fill = factor(expansion), 
             color = factor(expansion))) + 
  geom_histogram(position="identity", bins = 40) + 
  scale_color_manual(values=c("darkorange1", "deepskyblue4"), labels = c("Non-Expansion", "Expansion")) + 
  scale_fill_manual(values=c("orange1", "#E69F0000"), labels = c("Non-Expansion", "Expansion")) + 
  xlim(40, 100) + 
  ylim(0, .15) + 
  xlab("Insurance Rate [0-100]") +
  ggtitle("2012") +
  theme(legend.title = element_blank())


hist2016 <- mydata %>% filter(year == 2016) %>%
  ggplot(aes(x = pctic_0400, 
             after_stat(density), 
             group = expansion, 
             fill = factor(expansion), 
             color = factor(expansion))) + 
  geom_histogram(position="identity", bins = 55) + 
  scale_color_manual(values=c("darkorange1", "deepskyblue4"), labels = c("Non-Expansion", "Expansion")) + 
  scale_fill_manual(values=c("orange1", "#E69F0000"), labels = c("Non-Expansion", "Expansion")) + 
  xlim(40, 100) + 
  ylim(0, .15) + 
  xlab("Insurance Rate [0-100]") +
  ggtitle("2016") +
  theme(legend.title = element_blank())

  
  

cowplot::plot_grid(hist2012, 
                   hist2016, 
                   nrow = 2, 
                   labels = c("A", "B"))
```

## Replications/Reanalysis

```{r}
results <- data.frame()

vars <- c("voteshare_dem", 
          "voteshare_gop", 
          "voteshare_oth", 
          "turnout",
          "pctic_0400",
          "unemp_rate_cty",
          "percent_in_poverty",
          "perc_black",
          "perc_native",
          "perc_asian",
          "perc_hisp",
          "median_income",
          "dem_campaign_spending_gap",
          "total_campaign_spending",
          "pop_den_100k")

for(var in vars) {
  tmp <- mydata %>%
    mutate(applied = mydata[[var]]) %>%
    filter(!is.na(pop_total)) %>%
    filter(!is.na(applied)) %>%
    group_by(year) %>%
    summarise(mean = weighted.mean(applied, pop_total))
  y08 <- filter(tmp, year == 2008)$mean
  y12 <- filter(tmp, year == 2012)$mean
  y16 <- filter(tmp, year == 2016)$mean
  p0812 <- mydata  %>% filter(year == 2008 | year == 2012) %>% mutate(applied = .[[var]]) %>% lm(applied ~ year, data = ., weights = pop_total) %>% summary %>% coef  %>% .["year", "Pr(>|t|)"]
  p1216 <- mydata  %>% filter(year == 2012 | year == 2016) %>% mutate(applied = .[[var]]) %>% lm(applied ~ year, data = ., weights = pop_total) %>% summary %>% coef %>% .["year", "Pr(>|t|)"]
  tmp <- data.frame(var, y08, y12, y16, y12-y08, y16-y12, p0812, p1216)
  results <- rbind(results, tmp)
}


results$y08 <- round(results$y08, digits = 2)
results$y12 <- round(results$y12, digits = 2)
results$y16 <- round(results$y16, digits = 2)
results$y12...y08 <- round(results$y12...y08, digits = 2)
results$y16...y12 <- round(results$y16...y12, digits = 2)


for (i in 1:15) {
  y12...y08 <- as.character(results[i, "y12...y08"])
  if (results[i, "p0812"] < 0.01) {
    y12...y08 <- paste(y12...y08, "***")
  } else if (results[i, "p0812"] < 0.05) {
      y12...y08 <-paste(y12...y08, "**")
  } else if (results[i, "p0812"] < 0.1) {
      y12...y08 <- paste(y12...y08, "*")
  }
  results[i, "y12...y08"] <- y12...y08
}

for (i in 1:15) {
  y16...y12 <- as.character(results[i, "y16...y12"])
  if (results[i, "p1216"] < 0.01) {
    y16...y12 <- paste(y16...y12, "***")
  } else if (results[i, "p1216"] < 0.05) {
      y16...y12 <-paste(y16...y12, "**")
  } else if (results[i, "p1216"] < 0.1) {
      y16...y12 <- paste(y16...y12, "*")
  }
  results[i, "y16...y12"] <- y16...y12
}


library(kableExtra)
library(knitr)
results %>% select(-p0812, -p1216) %>% kable(col.names = c("Variable", "2008", "2012", "2016", "2008–12 Difference", "2012–16 Difference"), type = "html") %>%
  kable_styling() %>%
  column_spec(column = c(5, 6),bold=T)
detach(package:kableExtra)
detach(package:knitr)
```


```{r}
library(estimatr)
demlm <- lm_robust(voteshare_dem ~ pctic_0400 + 
                      unemp_rate_cty +
                      percent_in_poverty +
                      perc_black +
                      perc_native +
                      perc_asian +
                      perc_hisp +
                      median_income +
                      dem_campaign_spending_gap +
                      total_campaign_spending +
                      pop_den_100k, 
          data = mydata,
          weights = pop_total,
          clusters = state,
          fixed_effects = ~ year + combined_fips,
          `se_type` = "CR0")
goplm <- lm_robust(voteshare_gop ~ pctic_0400 + 
                      unemp_rate_cty +
                      percent_in_poverty +
                      perc_black +
                      perc_native +
                      perc_asian +
                      perc_hisp +
                      median_income +
                      dem_campaign_spending_gap +
                      total_campaign_spending +
                      pop_den_100k, 
          data = mydata,
          weights = pop_total,
          clusters = state,
          fixed_effects = ~ year + combined_fips,
          `se_type` = "CR0")
othlm <- lm_robust(voteshare_oth ~ pctic_0400 + 
                      unemp_rate_cty +
                      percent_in_poverty +
                      perc_black +
                      perc_native +
                      perc_asian +
                      perc_hisp +
                      median_income +
                      dem_campaign_spending_gap +
                      total_campaign_spending +
                      pop_den_100k, 
          data = mydata,
          weights = pop_total,
          clusters = state,
          fixed_effects = ~ year + combined_fips,
          `se_type` = "CR0")

turnlm <- lm_robust(turnout ~ pctic_0400 + 
                      unemp_rate_cty +
                      percent_in_poverty +
                      perc_black +
                      perc_native +
                      perc_asian +
                      perc_hisp +
                      median_income +
                      dem_campaign_spending_gap +
                      total_campaign_spending +
                      pop_den_100k, 
          data = mydata,
          weights = pop_total,
          clusters = state,
          fixed_effects = ~ year + combined_fips,
          `se_type` = "CR0")


results <- data.frame()
results <- rbind(results, data.frame(estoth = summary(othlm)$coefficients[,"Estimate"],
                                     erroth = summary(othlm)$coefficients[,"Std. Error"],
                                     pvaloth = summary(othlm)$coefficients[,"Pr(>|t|)"],
                                     vars = rownames(summary(othlm)$coefficients)))
results <- cbind(results, data.frame(estgop = summary(goplm)$coefficients[,"Estimate"],
                                     errgop = summary(goplm)$coefficients[,"Std. Error"],
                                     pvalgop = summary(goplm)$coefficients[,"Pr(>|t|)"]))
results <- cbind(results, data.frame(estdem = summary(demlm)$coefficients[,"Estimate"],
                                     errdem = summary(demlm)$coefficients[,"Std. Error"],
                                     pvaldem = summary(demlm)$coefficients[,"Pr(>|t|)"]))
results <- cbind(results, data.frame(estturn = summary(turnlm)$coefficients[,"Estimate"],
                                     errturn = summary(turnlm)$coefficients[,"Std. Error"],
                                     pvalturn = summary(turnlm)$coefficients[,"Pr(>|t|)"]))


results[,-4] <- round(results[,-4], digits = 2)

for (i in 1:11) {
  est <- as.character(results[i, "estoth"])
    if (results[i, "pvaloth"] < 0.01) {
    est <- paste(est, "***")
  } else if (results[i, "pvaloth"] < 0.05) {
      est <-paste(est, "**")
  } else if (results[i, "pvaloth"] < 0.1) {
      est <- paste(est, "*")
  }
  est <- paste0(est, "<br>", "(", as.character(results[i, "erroth"]), ")")
  results[i, "Other Party Vote Share"] <- est
}

for (i in 1:11) {
  est <- as.character(results[i, "estdem"])
    if (results[i, "pvaldem"] < 0.01) {
    est <- paste(est, "***")
  } else if (results[i, "pvaldem"] < 0.05) {
      est <-paste(est, "**")
  } else if (results[i, "pvaldem"] < 0.1) {
      est <- paste(est, "*")
  }
  est <- paste0(est, "<br>", "(", as.character(results[i, "errdem"]), ")")
  results[i, "Democratic Party Vote Share"] <- est
}

for (i in 1:11) {
  est <- as.character(results[i, "estgop"])
    if (results[i, "pvalgop"] < 0.01) {
    est <- paste(est, "***")
  } else if (results[i, "pvalgop"] < 0.05) {
      est <-paste(est, "**")
  } else if (results[i, "pvalgop"] < 0.1) {
      est <- paste(est, "*")
  }
  est <- paste0(est, "<br>", "(", as.character(results[i, "errgop"]), ")")
  results[i, "GOP Party Vote Share"] <- est
}

for (i in 1:11) {
  est <- as.character(results[i, "estturn"])
    if (results[i, "pvalturn"] < 0.01) {
    est <- paste(est, "***")
  } else if (results[i, "pvalturn"] < 0.05) {
      est <-paste(est, "**")
  } else if (results[i, "pvalturn"] < 0.1) {
      est <- paste(est, "*")
  }
  est <- paste0(est, "<br>", "(", as.character(results[i, "errturn"]), ")")
  results[i, "Voter Turnout"] <- est
}


library(kableExtra)
results %>% select("Democratic Party Vote Share", "GOP Party Vote Share", "Other Party Vote Share", "Voter Turnout") %>% knitr::kable("html", escape = F) %>% kable_styling()

```


## Summary/Discussion

[How successful were you at replicating the analyses and visualizations in the study? What problems did you encounter? Why might you have encountered those problems? What details were lacking from the original study's methods that might have hampered your ability to replicate the authors' results?]

## References